# Generated by Django 5.0.6 on 2024-06-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='mobile_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
