# Generated by Django 5.0.6 on 2024-06-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_management', '0002_alter_driver_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='mobile_number',
            field=models.CharField(max_length=18),
        ),
    ]
