# Generated by Django 5.0.6 on 2024-06-15 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_management', '0003_driver_id_alter_driver_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=15, unique=True)),
                ('registration_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_truck',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='truck_management.truck'),
        ),
    ]
